version: "3.2"

services:
    web:
        build: ./web
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - type: bind
              source: ./web
              target: /home/node/code
        stdin_open: true
        tty: true
